# Generated by Django 5.2.3 on 2025-07-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_firtsname_userprofile_firt_sname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firt_sname',
            new_name='first_sname',
        ),
    ]
