# Generated by Django 5.2.3 on 2025-07-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_firt_sname_userprofile_first_sname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_sname',
            new_name='first_name',
        ),
    ]
