# Generated by Django 5.2.3 on 2025-07-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_first_sname_userprofile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
